In [1]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_csv("training_boston.csv")

In [47]:
df

# CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
..        ...       ...       ...       ...       ...       ...       ...   
374 -0.204929 -0.487722  1.231945  3.668398  0.434551  2.161728  1.053485   
375  0.231398 -0.487722  1.015999 -0.272599  1.367490  0.215644  0.687212   
376 -0.408311 -0.487722  0.247057 -0.272599 -1.016689 -0.206055 -0.809889   
377 -0.410620 -0.487722 -1.152214 -0.272599 -0.818007  0.068904 -1.826921   
378  0.342909 -0.487722  1.015999  3.668398  0.659147  1.041946  1.028593   

          DIS       RAD       TAX   PTRATIO         B     LSTAT     Y  
0   -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  
1    0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  
2   -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  
3   -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  
4    0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5  
..        ...       ...       ...       ...       ...       ...   ...  
374 -0.833960 -0.523001 -0.031105 -1.736418  0.361122 -1.504494  50.0  
375 -0.703186  1.661245  1.530926  0.806576 -2.812183  0.499991  14.3  
376  0.140451 -0.523001 -0.060801  0.113032  0.332066 -0.334043  20.8  
377  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.744752  22.6  
378 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  50.0  

[379 rows x 14 columns]

In [52]:
df['x1'] = np.ones(379)

In [53]:
df

# CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
..        ...       ...       ...       ...       ...       ...       ...   
374 -0.204929 -0.487722  1.231945  3.668398  0.434551  2.161728  1.053485   
375  0.231398 -0.487722  1.015999 -0.272599  1.367490  0.215644  0.687212   
376 -0.408311 -0.487722  0.247057 -0.272599 -1.016689 -0.206055 -0.809889   
377 -0.410620 -0.487722 -1.152214 -0.272599 -0.818007  0.068904 -1.826921   
378  0.342909 -0.487722  1.015999  3.668398  0.659147  1.041946  1.028593   

          DIS       RAD       TAX   PTRATIO         B     LSTAT     Y   x1  
0   -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  1.0  
1    0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  1.0  
2   -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  1.0  
3   -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  1.0  
4    0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5  1.0  
..        ...       ...       ...       ...       ...       ...   ...  ...  
374 -0.833960 -0.523001 -0.031105 -1.736418  0.361122 -1.504494  50.0  1.0  
375 -0.703186  1.661245  1.530926  0.806576 -2.812183  0.499991  14.3  1.0  
376  0.140451 -0.523001 -0.060801  0.113032  0.332066 -0.334043  20.8  1.0  
377  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.744752  22.6  1.0  
378 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  50.0  1.0  

[379 rows x 15 columns]

In [35]:
X_test = np.loadtxt("test_boston.csv", delimiter = ',')

In [41]:
X_test.shape[1]

13

In [54]:
X_train = df.loc[:, df.columns!=" Y"]

In [55]:
df.columns

Index(['# CRIM', ' ZN', ' INDUS', ' CHAS', ' NOX', ' RM', ' AGE', ' DIS',
       ' RAD', ' TAX', ' PTRATIO', ' B', ' LSTAT', ' Y', 'x1'],
      dtype='object')

In [56]:
Y_train = df[" Y"]

In [17]:
X_train.shape

(379, 13)

### using direct sklearn function for gradient descent

In [23]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(X_train,Y_train)

GradientBoostingRegressor()

In [24]:
y_pred = model.predict(X_train)

In [28]:
from sklearn.metrics import mean_squared_error
mse_self_implement = mean_squared_error(Y_train, y_pred)

In [29]:
mse_self_implement

1.9853817122497177

In [30]:
u = ((Y_train - y_pred)**2).sum()
v = ((Y_train - Y_train.mean())**2).sum()
score = 1 - u/v
print("Train score : ", score)

Train score :  0.9774216123881818


In [38]:
y_test_pred = model.predict(X_test)

In [120]:
y_test_pred.savetxt('gradient.csv')

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'

In [121]:
np.savetxt("gradient.csv", y_test_pred, delimiter=",")

### implementation gradient descent

In [ ]:
# This function finds the new gradient at each step
def step_gradient(X_train, Y_train, learning_rate, m , c):
    n = X_train.shape[1]
    m_slope = np.empty(n)
    M = len(X_train)
    for i in range(M):
        y = Y_train[i]
        for j in range(n):
            one = m_slope*X_train[i];
        
            
    new_m = m - learning_rate * m_slope
    new_c = c - learning_rate * c_slope
    return new_m, new_c

In [ ]:
# The Gradient Descent Function
def gd(X_train, Y_train, learning_rate, num_iterations):
    m = 0       # Intial random value taken as 0
    c = 0       # Intial random value taken as 0
    for i in range(num_iterations):
        m, c = step_gradient(X_train, Y_train, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

In [ ]:
def run():
    alpha = 0.001
    iterate = 100
    m, c = gd(X_train, Y_train alpha, iterate)
    

In [61]:
X_train = np.array(X_train)

In [64]:
X_train[0]

array([-0.40784991, -0.48772236, -1.2660231 , -0.27259857, -0.57613394,
        1.23997392,  0.84012202, -0.52026428, -0.75292215, -1.27835435,
       -0.30309415,  0.41057102, -1.09799011,  1.        ])

In [114]:
n = X_train.shape[1]
m_slope = np.zeros(n)

In [116]:
m_slope*X_train[0]

array([-0., -0., -0., -0., -0.,  0.,  0., -0., -0., -0., -0.,  0., -0.,
        0.])

In [117]:
m_slope.shape

(14,)

In [118]:
arr = X_train[0]

In [110]:
arr = arr.reshape(-1, 1)

In [111]:
arr.shape

(14, 1)

In [119]:
m_slope*arr

array([-0., -0., -0., -0., -0.,  0.,  0., -0., -0., -0., -0.,  0., -0.,
        0.])

In [98]:
m_slope.shape

(1, 14)

In [105]:
arr.shape

(14,)

In [101]:
X_train[0]

array([-0.40784991, -0.48772236, -1.2660231 , -0.27259857, -0.57613394,
        1.23997392,  0.84012202, -0.52026428, -0.75292215, -1.27835435,
       -0.30309415,  0.41057102, -1.09799011,  1.        ])

In [104]:
arr.shape

(14,)